version: '3.7'

services:

  ifps.sqlserver:
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "Asdf123."
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
      DB_SALES_NAME: IFPSSalesDb
      DB_SALES_HANGFIRE_NAME: IFPSSalesHangfireDb
      DB_FACTORY_NAME: IFPSFactoryDb
      DB_INTEGRATION_HANGFIRE_NAME: IFPSIntegrationHangfireDb
    restart: always
        
  ifps.sales.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=80
      - ConnectionStrings__DefaultConnection=Server=ifps.sqlserver;Database=IFPSSalesDb;User=SA;Password=Asdf123.
      - Serilog__WriteTo__0__Args__configure__0__Args__connectionString=Server=ifps.sqlserver;Database=IFPSSalesDb;User=SA;Password=Asdf123.
      - Logging__LogLevel__Default=Debug
      - Site__BaseUrl=http://localhost:4201
      - AllowedHosts=*
      - Cors__AllowedOrigins__0=http://localhost:4201
      - Cors__AllowedOrigins__1=http://localhost:4221
    ports:
      - "5020:80"   
    restart: always
      
  ifps.sales.ui:
    ports:
      - "4201:80"
    environment:
      - API_URL=http://localhost:5020
    restart: always

  ifps.webshop.ui:
    ports:
      - "4221:80"
    environment:
      - API_URL=http://localhost:5020
    restart: always
  
  ifps.factory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=80
      - ConnectionStrings__DefaultConnection=Server=ifps.sqlserver;Database=IFPSFactoryDb;User=SA;Password=Asdf123.
      - Serilog__WriteTo__0__Args__configure__0__Args__connectionString=Server=ifps.sqlserver;Database=IFPSFactoryDb;User=SA;Password=Asdf123.
      - Logging__LogLevel__Default=Debug
      - Site__BaseUrl=http://localhost:4211
      - AllowedHosts=*
      - Cors__AllowedOrigins__0=http://localhost:4211
    ports:
      - "5030:80"  
    restart: always
      
  ifps.factory.ui:
    ports:
      - "4211:80"
    environment:
      - API_URL=http://localhost:5030
    restart: always
        
  ifps.integration.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=80
      - ConnectionStrings__SalesConnection=Server=ifps.sqlserver;Database=IFPSSalesDb;User=SA;Password=Asdf123.
      - ConnectionStrings__FactoryConnection=Server=ifps.sqlserver;Database=IFPSFactoryDb;User=SA;Password=Asdf123.
      - Serilog__WriteTo__0__Args__configure__0__Args__connectionString=Server=ifps.sqlserver;Database=IFPSFactoryDb;User=SA;Password=Asdf123.
      - Site__BaseUrl=http://localhost:5040
      - APIURLs__SalesURL=http://localhost:5020
      - APIURLs__FactoryURL=http://localhost:5030
      - AllowedHosts=*
    ports:
      - "5040:80"   
    restart: always
  