apiVersion: v1
kind: Service
metadata:
  name: butor-integration-api
  labels:
    app.kubernetes.io/name: butor-integration-api
    tier: backend 
    environment: dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http 
      name: http 
  selector:
    app.kubernetes.io/name: butor-integration-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: butor-integration-api
  labels:
    app.kubernetes.io/name: butor-integration-api
    tier: backend 
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: butor-integration-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: butor-integration-api
        tier: backend 
        environment: dev
    spec:
      containers:
        - name: butor-integration-api
          image: registry.encosoft-dev.hu/butorrevolution/integration-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_HTTP_PORT
              value: "80"
            - name: ConnectionStrings__SalesConnection
              value: 'Server=butor-db;Database=IFPSSalesDb;User=SA;Password=Asdf123.'
            - name: ConnectionStrings__FactoryConnection
              value: 'Server=butor-db;Database=IFPSFactoryDb;User=SA;Password=Asdf123.'
            - name: ConnectionStrings__HangfireConnection
              value: 'Server=butor-db;Database=IFPSIntegrationHangfireDb;User=SA;Password=Asdf123.'
            - name: Logging__LogLevel__Default
              value: 'Debug'
            - name: Site__BaseUrl
              value: 'http://integration.butor.k8s.encosoft-dev.hu'
            - name: APIURLs__FactoryURL
              value: 'http://factory.butor.k8s.encosoft-dev.hu'
            - name: APIURLs__SalesURL
              value: 'http://sales.butor.k8s.encosoft-dev.hu'
            - name: APIURLs__IntegrationURL
              value: 'http://integration.butor.k8s.encosoft-dev.hu/api/synchronization'
            - name: AllowedHosts
              value: '*'
      imagePullSecrets:
      - name: harbor-credential
      restartPolicy: Always
      
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: butor-integration-api
  labels:
    app.kubernetes.io/name: butor-integration-api
    tier: backend 
    environment: dev
spec:
  rules:
  - host: integration.butor.k8s.encosoft-dev.hu
    http:
      paths:
      - path: /api
        backend:
          serviceName: butor-integration-api 
          servicePort: http 
