apiVersion: v1
kind: Service
metadata:
  name: butor-db
  labels:
    app.kubernetes.io/name: butor-db
    tier: database 
    environment: dev
spec:
  ports:
    - port: 1433
      protocol: TCP
  selector:
    app.kubernetes.io/name: butor-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: butor-db
  labels:
    app.kubernetes.io/name: butor-db
    tier: database 
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: butor-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: butor-db
        tier: database 
        environment: dev
    spec:
      containers:
        - name: butor-db
          image: registry.encosoft-dev.hu/butorrevolution/sqlserver:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "Asdf123."
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Express
            - name: DB_SALES_NAME
              value: IFPSSalesDb
            - name: DB_SALES_HANGFIRE_NAME
              value: IFPSSalesHangfireDb
            - name: DB_FACTORY_NAME
              value: IFPSFactoryDb
            - name: DB_INTEGRATION_HANGFIRE_NAME
              value: IFPSIntegrationHangfireDb
      imagePullSecrets:
      - name: harbor-credential
      restartPolicy: Always
