apiVersion: v1
kind: Service
metadata:
  name: butor-sales-api
  labels:
    app.kubernetes.io/name: butor-sales-api
    tier: backend 
    environment: dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http 
      name: http 
  selector:
    app.kubernetes.io/name: butor-sales-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: butor-sales-api
  labels:
    app.kubernetes.io/name: butor-sales-api
    tier: backend 
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: butor-sales-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: butor-sales-api
        tier: backend 
        environment: dev
    spec:
      containers:
        - name: butor-sales-api
          image: registry.encosoft-dev.hu/butorrevolution/sales-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_HTTP_PORT
              value: "80"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=butor-db;Database=IFPSSalesDb;User=SA;Password=Asdf123."
            - name: ConnectionStrings__HangfireConnection
              value: "Server=butor-db;Database=IFPSSalesHangfireDb;User=SA;Password=Asdf123."
            - name: Site__BaseUrl
              value: "http://sales.butor.k8s.encosoft-dev.hu"
            - name: APIURLs__FactoryURL
              value: "http://factory.butor.k8s.encosoft-dev.hu"
            - name: APIURLs__SalesURL
              value: "http://sales.butor.k8s.encosoft-dev.hu"
            - name: AllowedHosts
              value: "*"
            - name: Logging__LogLevel__Default
              value: 'Debug'
      imagePullSecrets:
      - name: harbor-credential
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: butor-sales-api
  labels:
    app.kubernetes.io/name: butor-sales-api
    tier: backend 
    environment: dev
#  annotations:
#    traefik.ingress.kubernetes.io/request-modifier: "AddPrefix: /api"
spec:
  rules:
  - host: sales.butor.k8s.encosoft-dev.hu
    http:
      paths:
      - path: /api
        backend:
          serviceName: butor-sales-api 
          servicePort: http 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: butor-sales-api-bare
  labels:
    app.kubernetes.io/name: butor-sales-api
    tier: backend 
    environment: dev
#  annotations:
#    traefik.ingress.kubernetes.io/request-modifier: "AddPrefix: /api"
spec:
  rules:
  - host: salesapi.butor.k8s.encosoft-dev.hu
    http:
      paths:
      - path: /
        backend:
          serviceName: butor-sales-api 
          servicePort: http 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: butor-sales-api-ws
  labels:
    app.kubernetes.io/name: butor-sales-api
    tier: backend 
    environment: dev
#  annotations:
#    traefik.ingress.kubernetes.io/request-modifier: "AddPrefix: /api"
spec:
  rules:
  - host: webshop.butor.k8s.encosoft-dev.hu
    http:
      paths:
      - path: /api
        backend:
          serviceName: butor-sales-api 
          servicePort: http 
